### PR TITLE
Add missing header

### PR DESCRIPTION
**Pull request by chasingegg**
https://github.com/milvus-io/milvus/actions/runs/6199723284/job/16832875500?pr=27146
/kind improvement

### CODE REVIEW

**Comment by liliu-z** [comment]
Why we don't met any issue before?

**Comment by chasingegg** [comment]
I have met one when implementing scann index, https://github.com/zilliztech/knowhere/pull/8 which is failed at milvus mac code checker rule. I guess we could align the code checker rule of milvus and knowhere.

**Pull request merged**
