### PR TITLE
The final candidate of the version that uses Faiss 1.7.4

### PR DESCRIPTION
**Pull request by alexanderguzhva**
Finalized version of https://github.com/zilliztech/knowhere/pull/90
Based on Faiss 1.7.4 (based on commit c8d6f7bb2b09b8928570222131353f75acb4007b from Sep 6 2023, but with all the most recent merged commits).

Issue #186 

The following changes were made to Knowhere besides refactoring:
* All `BitsetView` filtering is replaced with `faiss::IDSelector` filtering.
* So-called “thread-safe” functions were deleted. Instead, regular `search()`/`range_search()` are used with `faiss::SearchParameters` objects as a function parameter.
* `faiss::elkan_L2_sse()` call is used by default as before, but IVF-indices in Knowhere (`ivf.cc`) introduce a new flag “use_elkan” (false by default), which allows to significantly speed up the training 

/kind enhancement

### CODE REVIEW

**Comment by zhengbuqian** [comment]
/lgtm

Thanks Alex!
Looked at files in directory other than `thirdparty/faiss`.

**Comment by liliu-z** [comment]
/approve

Plz resolve the conflicts and link an issue with this PR. Thanks~

**Review by chasingegg — COMMENTED** [review]
/lgtm

**Comment by liliu-z** [comment]
link to PR notes: https://docs.google.com/document/d/15i4uXO5MdAYVW5yikX2PzECYmcVIo5TndZ2w4-m62Oc/edit

**Pull request merged**
