### PR TITLE
PRQ: set default 'nrq' value to 2

### PR DESCRIPTION
**Pull request by alexanderguzhva**
issue https://github.com/milvus-io/milvus/issues/36922

/kind enhancement

### CODE REVIEW

**Review by liliu-z — APPROVED** [review]
/lgtm

**Comment by alexanderguzhva** [comment]
superseded by #904

**Review by liliu-z — APPROVED** [review]
/lgtm

**Comment by alexanderguzhva** [comment]
superseded by #913

**Pull request closed without merging**
