### PR TITLE
Implement BF16 scalar quantizer for faiss

### PR DESCRIPTION
**Pull request by alexanderguzhva**
Corresponding faiss PR: https://github.com/facebookresearch/faiss/pull/3444

/kind improvement

### CODE REVIEW

**Comment by liliu-z** [comment]
Are we trying to align the code with FAISS? If so why we don't just pull new versions?

**Comment by alexanderguzhva** [comment]
I do it from time to time, while cherry-picking the most important PRs asap

**Comment by alexanderguzhva** [comment]
@liliu-z fyi, faiss has committed this PR to the baseline

**Comment by alexanderguzhva** [comment]
superseded by #663

**Pull request closed without merging**
