### PR TITLE
Initial ppc64le support

### PR DESCRIPTION
**Pull request by mgiessing**
This PR aims to support the build process of knowhere for ppc64le architecture: https://github.com/zilliztech/knowhere/issues/161

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
@mgiessing could you please squash your commits? It is a preferred way for knowledge to have a single commit for a PR. Thanks

**Comment by mgiessing** [comment]
@alexanderguzhva Just squashed the commits - thanks!

**Comment by mgiessing** [comment]
@alexanderguzhva  I'm not sure what's still wrong
I installed the pre-commit hook, run the clang-formatting (which apparently also changed formatting of 2 other files) and when pushed it everything looked fine. Nonetheless gh actions complains about it :/

**Comment by mgiessing** [comment]
@mgiessing That would be one option, however on the other hand I'm also thinking about adding vector intrinsic code for the distance calculation (i.e. adding `distances_vsx.cc` & `distances_vsx.h`. However that would probably take some more time to accomplish.

**Comment by liliu-z** [comment]
#161

**Comment by liliu-z** [comment]
> @liliu-z That would be one option, however on the other hand I'm also thinking about adding vector intrinsic code for the distance calculation (i.e. adding `distances_vsx.cc` & `distances_vsx.h`. However that would probably take some more time to accomplish.

Sure, Thanks for this.
Before merging in, can you help:
1. Revert the format change for `include/knowhere/dataset.h` and `benchmark/benchmark_base.h` to pass the pre-commit check. Sorry about this inconsistent experience it brings. We will take a look but we can bypass it for now.
2. Remake the commit message by `git --amend -s` to add the signature.

Thanks

**Comment by samhuang-z** [comment]
this solves: https://github.com/zilliztech/knowhere/issues/161

**Comment by mgiessing** [comment]
@liliu-z this is very weird. If I follow the Contributing guidelines and install the pre-commit hook locally I get a FAILED because of the two mentioned files:

```bash
$ git push
check for added large files..............................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

benchmark/benchmark_base.h
====================
--- original

+++ formatted

@@ -188,10 +188,10 @@

     void
     free_all() {
         if (xb_ != nullptr) {
-            delete[](float*) xb_;
+            delete[] (float*)xb_;
         }
         if (xq_ != nullptr) {
-            delete[](float*) xq_;
+            delete[] (float*)xq_;
         }
         if (gt_radius_ != nullptr) {
             delete[] gt_radius_;
include/knowhere/dataset.h
====================
--- original

+++ formatted

@@ -36,25 +36,25 @@

             {
                 auto ptr = std::get_if<0>(&x.second);
                 if (ptr != nullptr) {
-                    delete[] * ptr;
+                    delete[] *ptr;
                 }
             }
             {
                 auto ptr = std::get_if<1>(&x.second);
                 if (ptr != nullptr) {
-                    delete[] * ptr;
+                    delete[] *ptr;
                 }
             }
             {
                 auto ptr = std::get_if<2>(&x.second);
                 if (ptr != nullptr) {
-                    delete[] * ptr;
+                    delete[] *ptr;
                 }
             }
             {
                 auto ptr = std::get_if<3>(&x.second);
                 if (ptr != nullptr) {
-                    delete[](char*)(*ptr);
+                    delete[] (char*)(*ptr);
                 }
             }
         }

error: failed to push some refs to 'https://github.com/mgiessing/knowhere'
```

I'm wondering you don't get this, FYI I use clang-format 17.0.6:

```bash
$ clang-format --version
Homebrew clang-format version 17.0.6
```
Nevertheless I try to uninstall the hook and push again

**Comment by liliu-z** [comment]
/lgtm 
Thanks~

**Comment by sumitd2** [comment]
@mgiessing Do you have any update on the SIMD optimizations? Thanks.

**Comment by mgiessing** [comment]
I briefly had a look into manually creating VSX code however the auto-vectorizer seems to do a pretty good job and there was no real benefit when I compared handwritten VSX code (which might not be perfect of course) vs. what the compiler generated.

**Pull request merged**
