### PR TITLE
fix iterator: set omp to 1

### PR DESCRIPTION
**Pull request by alwayslove2013**
Use search_pool to handle iterator's next_batch instead of init

### CODE REVIEW

**Comment by cydrain** [comment]
Generally e2e should finish in 30 minutes.
Comparing a success e2e run with yours
```
success e2e run:
[2024-12-17 04:35:58 - INFO - test_func.py:48]: Start building index, index_type = HNSW, metric_type = L2
[2024-12-17 04:36:00 - INFO - test_func.py:39]: ### check_build_index runtime: 2.301s
[2024-12-17 04:36:00 - INFO - test_func.py:39]: ### iterator_search runtime: 0.023s
[2024-12-17 04:36:00 - INFO - test_func.py:39]: ### iterator_search runtime: 0.055s
[2024-12-17 04:36:01 - INFO - test_func.py:39]: ### iterator_search runtime: 0.219s

yours:
[2024-12-17 06:58:15 - INFO - test_func.py:48]: Start building index, index_type = HNSW, metric_type = L2
[2024-12-17 06:58:17 - INFO - test_func.py:39]: ### check_build_index runtime: 2.460s
```

I cannot see "iterator_search runtime" in your e2e log, there must be something wrong

**Comment by alexanderguzhva** [comment]
@alwayslove2013 is it good to review this PR? thanks

**Comment by alwayslove2013** [comment]
@alexanderguzhva Sorry, there are still some compatibility issues with bruteforce-iterator. I will fix it asap. please hold~

**Pull request closed without merging**
