### PR TITLE
Binary vector from/to np.uint8 array in pyknowhere api 

### PR DESCRIPTION
**Pull request by chasingegg**
issue #546 

Currently binary vector dataset uses np.int32, change to np.uint8

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
do I get it correct that we don't need to maintain the backward compatibility for this particular case?

**Comment by chasingegg** [comment]
> do I get it correct that we don't need to maintain the backward compatibility for this particular case?

I guess so, we never officially manage the pyknowhere release

**Pull request merged**
