### PR TITLE
fix async bug

### PR DESCRIPTION
**Pull request by Presburger**
@alexanderguzhva help review

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
/lgtm
@Presburger Personally, I would use `std::shared_ptr<Json>` to avoid copying, but passing just `json` is fine as well.

**Comment by Presburger** [comment]
> /lgtm @Presburger Personally, I would use `std::shared_ptr<Json>` to avoid copying, but passing just `json` is fine as well.

Alex, your suggestion is correct, but changing it to `shared_ptr` would require quite a few API modifications. 😂

**Comment by Presburger** [comment]
issue: #890

**Pull request merged**
