### PR TITLE
Fix a problem with faiss simdlib use v2

### LINKED ISSUE #149: [Faiss] some issues in Faiss::simdlib after #144
#144 allows to compile faiss, faiss_avx2 and faiss_avx512 library codes, depending on the CPU architecture. It seems that faiss (that uses SSE4.2) code leads to use of `simd_emulated.h` file instead of `simd_avx2.h`, and this file triggers run-time SIGSEGV error and incorrect results while running SCANN unittests for Knowhere.

### PR DESCRIPTION
**Pull request by chasingegg**
Try fix #149  cc @alexanderguzhva                            
/kind bug

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
/lgtm
I could not crash the unit tests :)

**Comment by chasingegg** [comment]
@Presburger help try this patch to verify if it is ok under your settings.

**Comment by alexanderguzhva** [comment]
Something stopped making sense to me. The performance of SCANN should be the same, no matter whether I use `-mfma -mavx2` for building `faiss`, right? But it is different.
/hold

**Pull request merged**
