### PR TITLE
ivf_sq support iterator

### PR DESCRIPTION
**Pull request by cqy123456**
issue: https://github.com/zilliztech/knowhere/issues/771

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
/hold
would it be possible to NOT to apply a formatting to Faiss files, because it may significantly complicate merges from the Faiss baseline into our code?
Changes from
```
    replace_invlists(new ConcurrentArrayInvertedLists(nlist, code_size, ssize, is_cosine), true);
```
into
```
    replace_invlists(
            new ConcurrentArrayInvertedLists(
                    nlist, code_size, ssize, is_cosine),
            true);
```
are meaningless.

**Review by liliu-z — APPROVED** [review]
/lgtm

**Comment by liliu-z** [comment]
Don't forget to add tags and unhold

**Pull request merged**
